#
# This YAML file specifies the Face The Internet client and server setup 
# Compose file reference: https://docs.docker.com/compose/compose-file/
# 
#############################
# Server
#############################
server:
  container_name: face-the-internet-server
  #image: eduwass/face-the-internet-worker
  domainname: face-the-internet-server.dev
  hostname: face-the-internet-server
  build: ./server
  ports:
    - "1337:1337"
  volumes:
    - ./server:/app

#############################
# Client
#############################
client:
  container_name: face-the-internet-client
  #image: johnrobertpett/face-the-internet
  domainname: face-the-internet-client.dev
  hostname: face-the-internet-client
  build: ./client
  ports:
     - "3000:3000"
  volumes:
   - ./client:/app


